### ISSUE TITLE
runmqsc not responding

### ISSUE THREAD

**Issue by bintoo** [ibm-messaging/mq-appliance#13]
Hi

I have successfully use the Python MQ appliance cli to login MQ appliance and issue basic command like dspmq ect.

However, when I try to use runmqsc issue command against any queue manager,  it always timeout without any response.

Is there any way to fix this?

Thanks

**Comment by jamie-squibb** [comment]
Hi @bintoo, thank you for opening this issue.

The version of the MQ CLI client that you have downloaded does not currently support _runmqsc_. I will use this issue to enhance it for you. The MQ CLI client uses _expect_ to interact with the MQ Appliance CLI. The _expect_ utility requires a command prompt to be presented when the previous command has completed and the next command can be entered. The hang/timeout that you have observed occurs because the MQ CLI client is waiting for the _mqa(mqcli) #_ command prompt to be output to indicate that _runmqsc_ has completed, but the _runmqsc_ command is waiting for MQSC input.

**Comment by jamie-squibb** [comment]
Hi @bintoo, I have now enhanced the MQ CLI client to support _runmqsc_. Please see the updated documentation for how to use the client to execute MQSC commands. I hope this helps!

**Comment by bintoo** [comment]
Hi @jamie-squibb 

Thanks for your quick response,  Yes it is working now.  much appreciated. 

Just a general question that hopefully you will be able to help.  The reason I am looking for a cli client to run runmqsc command to MQ appliance is I was asked by my team to build a jenkin ci/cd pileline for provisioning queue manager on MQ appliance.  But I am unable to find any relevant example online,   just wondering are you able to point me to the right direction on where to start?  like some online example etc?

Many thanks again.

**Comment by jamie-squibb** [comment]
Hi @bintoo, unfortunately I'm not aware of any online examples of a Jenkins CI/CD pipeline for the MQ Appliance that I can direct you to. However, most steps will be either the same as, or similar to, provisioning a queue manager on other platforms.
